Repository silverstripe/silverstripe-comments, pull requests merged in 2018-03, with the labels that each got.

#235 Use FunctionalTest instead of SapphireTest to disable themes.
  tests/CommentsExtensionTest.php
Labels: affects/v4, change/patch

#236 FIX backport fix for lack of HTMLPurifier breakage
  code/model/Comment.php
Labels: affects/v3, change/patch, effort/easy, impact/critical, type/bug

#237 FIX Skip test if optional dependency not present
  tests/CommentsTest.php
Labels: affects/v3, change/patch, effort/easy, impact/low, type/bug

#240 Tiny bug fixes to work with SS4.
  src/Forms/CommentForm.php
Labels: affects/v4, change/patch
